### ISSUE TITLE
Hide and show main toolbar

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#176]
Is there a way to programmatically hide and show the main toolbar in the editor?

**Comment by SteveSchreiner** [comment]
I'm able to do it via:

$('.te-toolbar-section').css('display', 'none');

but is there an easier way?

**Comment by sohee-lee7** [comment]
@SteveSchreiner Sorry for late reply. Currently there is no easy way to hide and show tool bar. We did not consider this feature, so if you need this feature please make a new issue for supporting api for visibility of toolbar. I will close this issue because this issue so old. Again sorry for late reply.
