### ISSUE TITLE
How to switch between Write and Preview modes programmatically?

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#178]
How to switch between Write and Preview modes programmatically?

![image](https://user-images.githubusercontent.com/1679643/39881084-c7a09026-544d-11e8-9eec-201023040ed4.png)

**Comment by sohee-lee7** [comment]
@SteveSchreiner Sorry for late reply. We not support api for switch between Write and Preview.
When Write and Preview are switched, `te-tab-active` is changed in two points that are tab button and md container. So you could change class `te-tab-active` if you want to switch that.

![screen shot 2019-02-21 at 1 47 41 pm](https://user-images.githubusercontent.com/42666492/53144435-9973e800-35df-11e9-80e4-4c13ff07ae45.png)

This issue is old so I will close it. Again sorry for late. If you have problem, please make a new issue.

**Comment by mu-yu** [comment]
I toggle mode by code below and it works fine. @SteveSchreiner 

```javascript

const inactiveTab = Array
      .from(document.querySelectorAll('.te-markdown-tab-section .te-tab button'))
      .find( element => !element.classList.contains('te-tab-active'))

    inactiveTab && inactiveTab.click()
```
