### ISSUE TITLE
Disable automatic links

### ISSUE THREAD

**Issue by paulgrove** [nhnent/tui.editor#277]
This is a question or feature request rather than a bug... I hope you don't mind this being raised here.

If it is not appropriate here - please I would like to be directed to a good place to have a discussion on if it is possible now - or failing that how to best approach implementing such a feature.

## Version
1.2.6

## Test Environment
Any browser/OS

## Current Behaviour
Pasting or typing a url gets treated as a link automatically.  In some scenarios this is not desirable.

## Expected Behaviour
This behaviour be made optional.  Allowing only explicitly marked up links to be treated as such.  In particular I would use this in a comment section that discusses security vulnerabilities where by a link could be the subject of discussion as potentially being a malicious url which would not want to be accidentally clicked.

If this is possible now, please could you describe how it could be accomplished?

Thanks!

**Comment by ebicoglu** [comment]
actually the latest version doesn't automatically linkfy URLs.
how can I automatically make URLs as links.

**Comment by ebicoglu** [comment]
ok after long investigations; I see that the default behaviour of the TuiEditor doesn't linkify links.
Because markdown-it library's default options to linkify is false.
So I found a way to enable automatic linkifying links.

`window.tui.Editor.markdownitHighlight.options.linkify = true;`

@kyuwoo-choi , I think you can close this issue because the default behaviour of the editor is, just as the issue author wants

**Comment by sohee-lee7** [comment]
I'm sorry for late reply and thank @ebicoglu for investigations 👍 
This feature would be not implement so i will close issue.
If there is more needs for this feature, we consider then.
