### ISSUE TITLE
latest version toast editor does not support underline?

### ISSUE THREAD

**Issue by kwo2002** [nhnent/tui.editor#367]
I saw the [preview](http://uicdn.toast.com/tui-editor/tui-editor-preview-1520325258239.gif) on the [https://ui.toast.com/tui-editor/](https://ui.toast.com/tui-editor/)

preview movie toolbar has the underline icon. so I think, toast ui support the underline.

but I can't find the underline on toolbar.

Please help. Thanks

**Comment by sohee-lee7** [comment]
We did not originally support the underscore.

**Comment by Poxios** [comment]
### For those searching for a way to implement "toast ui underline"

While not a perfect solution, the method below works as a workaround. Since the Toast UI Editor API only provides the position of the selected text in the editor (not the exact HTML position), I implemented a manual replacement by temporarily marking the selected text and then replacing it in the HTML.

You can use this by adding a custom command and connecting it to a toolbar button.

* Command to add on editor load:
```js
editor.addCommand("wysiwyg", "underline", function () {
        const selectedText = editor.getSelectedText();
        const tempString = `__start__${selectedText}__end__`;
        editor.replaceSelection(tempString);
        const originalHtml = editor.getHTML();
        const newHtml = originalHtml.replaceAll("__start__", `<span style="text-decoration: underline;">`).replaceAll("__end__", `</span>`);
        editor.setHTML(newHtml);

        return true;
      });

```

* Toolbar button configuration:
```js
{
  name: "underline",
  tooltip: "Underline",
  command: "underline",
  text: "U",
  className: "toastui-editor-toolbar-icons",
  style: {
    backgroundImage: "none",
    color: "#333",
    fontWeight: "bold",
    textDecoration: "underline",
    fontSize: "16px",
  },
  state: "span",
}
```
